Upgrade QCXF to 3.15.3
jboss-fuse/camel-quarkus pull request #458
Opened 2024-11-13 14:12 UTC by JiriOndrusek

Backported https://github.com/apache/camel-quarkus/pull/6781

2024-11-13 14:13 UTC, JiriOndrusek commented
We need to wait for the PR u[stream to get merged.

2024-11-13 14:19 UTC, jamesnetherton commented on pom.xml
>          <quarkiverse-cxf-community.version>3.15.2</quarkiverse-cxf-community.version>
```suggestion
        <quarkiverse-cxf-community.version>3.15.3</quarkiverse-cxf-community.version>
```

2024-11-13 17:02 UTC, ppalaga requested changes
I'd vote for backporting https://github.com/apache/camel-quarkus/pull/6782 rather than https://github.com/apache/camel-quarkus/pull/6781

2024-11-14 07:21 UTC, JiriOndrusek commented
Sure, I'll do it

2024-11-14 08:50 UTC, JiriOndrusek commented
Superseded by https://github.com/jboss-fuse/camel-quarkus/pull/459

2024-11-14 08:50 UTC, closed without merging